# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: my@mail.com
author_name: John Doe
contract_name: edufi_contract
preset_name: production
project_name: algorand_edufi-contracts

