# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: my@mail.com
author_name: John Doe
cloud_provider: netlify
contract_name: edufi_contract
preset_name: production
project_name: algorand_edufi

